import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto } from '@next/font/google'
import localFont from '@next/font/local'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Roboto({ subsets: ['latin'] ,weight:['400','700']})
// const local = localFont({src:''})
export default function Home(props) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1 className={inter.className}>Load Main Page</h1>
          <Link href="/posts/[]" as="/posts/2">Home {props.star}</Link>
          <button onClick={()=>router.push('/posts/2')}>Click me</button>
      </main>
    </>
  )
}

export async function getStaticProps(context){
  console.log("static props")
  return{
    props:{star:7}
  }
}
